package Session05.MiniProject.test.java.com.fastfood;

import Session05.MiniProject.main.java.com.fastfood.exception.InsufficientStockException;
import Session05.MiniProject.main.java.com.fastfood.exception.InvalidOrderIdException;
import Session05.MiniProject.main.java.com.fastfood.model.Drink;
import Session05.MiniProject.main.java.com.fastfood.model.Food;
import Session05.MiniProject.main.java.com.fastfood.model.Order;
import Session05.MiniProject.main.java.com.fastfood.repository.MenuRepository;
import Session05.MiniProject.main.java.com.fastfood.repository.OrderRepository;
import Session05.MiniProject.main.java.com.fastfood.service.MenuService;
import Session05.MiniProject.main.java.com.fastfood.service.OrderService;
import Session05.MiniProject.main.java.com.fastfood.service.StatisticsService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class OrderServiceTest {

    private MenuService menuService;
    private OrderService orderService;
    private StatisticsService statisticsService;

    @BeforeEach
    void setUp() {
        Order.resetCounter();
        MenuRepository menuRepo = new MenuRepository();
        OrderRepository orderRepo = new OrderRepository();
        menuService = new MenuService(menuRepo);
        orderService = new OrderService(orderRepo, menuService);
        statisticsService = new StatisticsService(orderRepo);

        menuService.addMenuItem(new Food("F001", "Hamburger", 45000, 100, "Burger"));
        menuService.addMenuItem(new Drink("D001", "Coca Cola", 15000, 50, Drink.DrinkSize.M));
    }

    @Test
    @DisplayName("Tạo đơn hàng mới → trạng thái khởi tạo là PENDING")
    void testCreateOrder_statusIsPending() {
        Order order = orderService.createOrder();
        assertNotNull(order);
        assertEquals(Order.OrderStatus.PENDING, order.getStatus());
    }

    @Test
    @DisplayName("Tạo hai đơn hàng liên tiếp → ID tự động tăng và khác nhau")
    void testCreateOrder_autoGeneratedId() {
        Order o1 = orderService.createOrder();
        Order o2 = orderService.createOrder();
        assertNotEquals(o1.getOrderId(), o2.getOrderId());
    }

    @Test
    @DisplayName("Thêm 2 Hamburger (45k) vào đơn → tổng tiền là 90.000đ")
    void testAddItemToOrder_correctSubtotal()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 2);
        assertEquals(90000.0, order.getTotalPrice(), 0.01);
    }

    @Test
    @DisplayName("Thêm 5 Hamburger vào đơn → tồn kho giảm từ 100 xuống 95")
    void testAddItemToOrder_reducesStock()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 5);
        assertEquals(95, menuService.findById("F001").get().getStock());
    }

    @Test
    @DisplayName("Thêm món với ID đơn hàng không hợp lệ → ném InvalidOrderIdException")
    void testAddItemToOrder_invalidOrderId_throwsException() {
        assertThrows(InvalidOrderIdException.class,
                () -> orderService.addItemToOrder("INVALID", "F001", 1));
    }

    @Test
    @DisplayName("Thêm 999 món vượt tồn kho → ném InsufficientStockException")
    void testAddItemToOrder_insufficientStock_throwsException() {
        Order order = orderService.createOrder();
        assertThrows(InsufficientStockException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "F001", 999));
    }

    @Test
    @DisplayName("Thêm món với số lượng = 0 → ném IllegalArgumentException")
    void testAddItemToOrder_zeroQuantity_throwsException() {
        Order order = orderService.createOrder();
        assertThrows(IllegalArgumentException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "F001", 0));
    }

    @Test
    @DisplayName("Thanh toán đơn hàng hợp lệ → trạng thái chuyển sang PAID")
    void testPayOrder_changesStatusToPaid()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.payOrder(order.getOrderId());
        assertEquals(Order.OrderStatus.PAID, order.getStatus());
    }

    @Test
    @DisplayName("Thanh toán đơn hàng chưa có món → ném IllegalStateException")
    void testPayOrder_emptyOrder_throwsException() {
        Order order = orderService.createOrder();
        assertThrows(IllegalStateException.class,
                () -> orderService.payOrder(order.getOrderId()));
    }

    @Test
    @DisplayName("Hủy đơn hàng PENDING → trạng thái chuyển sang CANCELLED")
    void testCancelOrder_changesStatusToCancelled()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 5);
        orderService.cancelOrder(order.getOrderId());
        assertEquals(Order.OrderStatus.CANCELLED, order.getStatus());
    }

    @Test
    @DisplayName("Hủy đơn hàng → tồn kho các món được hoàn trả đầy đủ")
    void testCancelOrder_restoresStock()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 10);
        orderService.cancelOrder(order.getOrderId());
        assertEquals(100, menuService.findById("F001").get().getStock());
    }

    @Test
    @DisplayName("Thống kê → tổng doanh thu đúng từ các đơn đã PAID")
    void testStatistics_totalRevenue()
            throws InvalidOrderIdException, InsufficientStockException {
        Order o1 = orderService.createOrder();
        orderService.addItemToOrder(o1.getOrderId(), "F001", 2); // 90000
        orderService.payOrder(o1.getOrderId());

        Order o2 = orderService.createOrder();
        orderService.addItemToOrder(o2.getOrderId(), "D001", 1); // 18000
        orderService.payOrder(o2.getOrderId());

        assertEquals(108000.0, statisticsService.getTotalRevenue(), 0.01);
    }

    @Test
    @DisplayName("Thống kê → xác định đúng món bán chạy nhất")
    void testStatistics_bestSellingItem()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 5);
        orderService.addItemToOrder(order.getOrderId(), "D001", 2);
        orderService.payOrder(order.getOrderId());

        assertEquals("Hamburger", statisticsService.getBestSellingItem().get());
    }

    @Test
    @DisplayName("Thống kê → chỉ tính đơn PAID, bỏ qua đơn CANCELLED")
    void testStatistics_onlyCountsPaidOrders()
            throws InvalidOrderIdException, InsufficientStockException {
        Order paid = orderService.createOrder();
        orderService.addItemToOrder(paid.getOrderId(), "F001", 1);
        orderService.payOrder(paid.getOrderId());

        Order cancelled = orderService.createOrder();
        orderService.addItemToOrder(cancelled.getOrderId(), "F001", 3);
        orderService.cancelOrder(cancelled.getOrderId());

        assertEquals(1, statisticsService.getTotalPaidOrderCount());
        assertEquals(45000.0, statisticsService.getTotalRevenue(), 0.01);
    }

    // =========================================================
    // LOGIC TÍNH TIỀN ĐƠN HÀNG
    // =========================================================

    @Test
    @DisplayName("Tổng tiền đơn gồm Food + Drink(M) → 45.000 + 18.000 = 63.000đ")
    void testOrderTotal_mixedFoodAndDrink()
            throws InvalidOrderIdException, InsufficientStockException {
        // F001: 45000 x1 = 45000; D001 (size M: 15000*1.2=18000) x1 = 18000 → tổng
        // 63000
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.addItemToOrder(order.getOrderId(), "D001", 1);
        assertEquals(63000.0, order.getTotalPrice(), 0.01);
    }

    @Test
    @DisplayName("Tổng tiền đơn với Drink size L → giá gốc × 1.5 × số lượng")
    void testOrderTotal_drinkSizeLMultiplier()
            throws InvalidOrderIdException, InsufficientStockException {
        // Thêm Drink size L: 15000 * 1.5 = 22500
        menuService.addMenuItem(new Drink("D002", "Nước Cam", 15000, 50, Drink.DrinkSize.L));
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "D002", 2);
        // 22500 * 2 = 45000
        assertEquals(45000.0, order.getTotalPrice(), 0.01);
    }

    @Test
    @DisplayName("calculateTotal() → trả về đúng tổng tiền đơn hàng")
    void testCalculateTotal_delegatesToOrderTotalPrice()
            throws InvalidOrderIdException, InsufficientStockException {
        // calculateTotal() của OrderService phải trả về đúng tổng tiền đơn
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 3);
        // 45000 * 3 = 135000
        assertEquals(135000.0, orderService.calculateTotal(order.getOrderId()), 0.01);
    }

    @Test
    @DisplayName("calculateTotal() với ID không tồn tại → ném InvalidOrderIdException")
    void testCalculateTotal_invalidOrderId_throwsException() {
        assertThrows(InvalidOrderIdException.class,
                () -> orderService.calculateTotal("INVALID"));
    }

    // =========================================================
    // EXCEPTION KHI NHẬP SAI DỮ LIỆU
    // =========================================================

    @Test
    @DisplayName("Thêm món với số lượng âm (-1) → ném IllegalArgumentException")
    void testAddItemToOrder_negativeQuantity_throwsException() {
        Order order = orderService.createOrder();
        assertThrows(IllegalArgumentException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "F001", -1));
    }

    @Test
    @DisplayName("Thêm món với ID thực đơn không tồn tại → ném IllegalArgumentException")
    void testAddItemToOrder_nonExistentMenuItemId_throwsException() {
        Order order = orderService.createOrder();
        assertThrows(IllegalArgumentException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "NOTEXIST", 1));
    }

    @Test
    @DisplayName("Thêm món vào đơn đã PAID → ném IllegalStateException")
    void testAddItemToOrder_toPaidOrder_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.payOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "F001", 1));
    }

    @Test
    @DisplayName("Thêm món vào đơn đã CANCELLED → ném IllegalStateException")
    void testAddItemToOrder_toCancelledOrder_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.cancelOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.addItemToOrder(order.getOrderId(), "F001", 1));
    }

    @Test
    @DisplayName("Thanh toán với ID đơn hàng không tồn tại → ném InvalidOrderIdException")
    void testPayOrder_invalidOrderId_throwsException() {
        assertThrows(InvalidOrderIdException.class,
                () -> orderService.payOrder("INVALID"));
    }

    @Test
    @DisplayName("Thanh toán đơn đã PAID → ném IllegalStateException")
    void testPayOrder_alreadyPaid_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.payOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.payOrder(order.getOrderId()));
    }

    @Test
    @DisplayName("Hủy đơn với ID không tồn tại → ném InvalidOrderIdException")
    void testCancelOrder_invalidOrderId_throwsException() {
        assertThrows(InvalidOrderIdException.class,
                () -> orderService.cancelOrder("INVALID"));
    }

    @Test
    @DisplayName("Hủy đơn đã PAID → ném IllegalStateException")
    void testCancelOrder_alreadyPaid_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.payOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.cancelOrder(order.getOrderId()));
    }

    @Test
    @DisplayName("Hủy đơn đã CANCELLED → ném IllegalStateException")
    void testCancelOrder_alreadyCancelled_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.cancelOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.cancelOrder(order.getOrderId()));
    }

    @Test
    @DisplayName("Xóa món khỏi đơn đã PAID → ném IllegalStateException")
    void testRemoveItemFromOrder_onPaidOrder_throwsException()
            throws InvalidOrderIdException, InsufficientStockException {
        Order order = orderService.createOrder();
        orderService.addItemToOrder(order.getOrderId(), "F001", 1);
        orderService.payOrder(order.getOrderId());
        assertThrows(IllegalStateException.class,
                () -> orderService.removeItemFromOrder(order.getOrderId(), "F001"));
    }
}
